### ISSUE TITLE
PBE Implementation

### ISSUE THREAD

**Issue by WhosOn** [zayKenyon/VALORANT-rank-yoinker#106]
A cool feature would be the combability to use it in PBE and Normal Valorant

**Comment by OwOHamper** [comment]
It should work on pbe since the region is grabbed from valo logs? Can you please upload vry logs while running pbe

**Comment by WhosOn** [comment]
[2022.08.21-13.21.54] got region from logs '['pbe', ['na-1', 'pbe']]'
[2022.08.21-13.21.54] Api urls: pd_url: 'https://pd.pbe.a.pvp.net', glz_url: 'https://glz-na-1.pbe.a.pvp.net'
[2022.08.21-13.21.54] opened lockfile
[2022.08.21-13.21.54] got version from logs 'pbe-160-shipping-750412'
[2022.08.21-13.21.56] config opened
[2022.08.21-13.21.56] got cooldown with value '10'
[2022.08.21-13.21.57] retrieved agent dict: {None: None, '': '', 'dade69b4-4f5a-8528-247b-219e5a1facd6': 'Fade', '5f8d3a7f-467b-97f3-062c-13acf203c006': 'Breach', 'f94c3b30-42be-e959-889c-5aa313dba261': 'Raze', '22697a3d-45bf-8dd7-4fec-84a9e28c69d7': 'Chamber', '601dbbe7-43ce-be57-2a40-4abd24953621': 'KAY/O', '6f2a04ca-43e0-be17-7f36-b3908627744d': 'Skye', '117ed9e3-49f3-6512-3ccf-0cada7e3823b': 'Cypher', '320b2a48-4d9b-a075-30f1-1f93a9b638fa': 'Sova', '1e58de9c-4950-5125-93e9-a0aee9f98746': 'Killjoy', '707eab51-4836-f488-046a-cda6bf494859': 'Viper', 'eb93336a-449b-9c1b-0a54-a891f7921d69': 'Phoenix', '41fb69c1-4189-7b37-f117-bcaf1e96f1bf': 'Astra', '9f0d8ba9-4140-b941-57d3-a7ad57c6b417': 'Brimstone', 'bb2a4828-46eb-8cd1-e765-15848195d751': 'Neon', '7f94d92c-4234-0a36-9646-3a87eb8b5c89': 'Yoru', '569fdd95-4d10-43ab-ca70-79becc718b46': 'Sage', 'a3bfb853-43b2-7238-a4f1-ad90e9e46bcc': 'Reyna', '8e253930-4c05-31dd-1b6c-968525494517': 'Omen', 'add6443a-41bd-e414-f6ad-e58d267f4e95': 'Jett'}
[2022.08.21-13.21.57] retrieved map dict: {None: None, '/game/maps/ascent/ascent': 'Ascent', '/game/maps/bonsai/bonsai': 'Split', '/game/maps/canyon/canyon': 'Fracture', '/game/maps/duality/duality': 'Bind', '/game/maps/foxtrot/foxtrot': 'Breeze', '/game/maps/pitt/pitt': 'Pearl', '/game/maps/port/port': 'Icebox', '/game/maps/poveglia/range': 'The Range', '/game/maps/triad/triad': 'Haven'}
[2022.08.21-13.21.57] Dexz's Rank Tool v2.1
[2022.08.21-13.21.57] got version from logs 'pbe-160-shipping-750412'
[2022.08.21-13.21.57] fetch: url: 'custom', endpoint: https://shared.pbe.a.pvp.net/content-service/v3/content, method: get, response code: 400
[2022.08.21-13.21.57] Traceback (most recent call last):
  File "main.py", line 110, in <module>
  File "C:\Users\ALT-PC-1\Desktop\VALORANT-rank-yoinker-main\VALORANT-rank-yoinker-main\src\content.py", line 13, in get_latest_season_id
KeyError: 'Seasons'

**Comment by OwOHamper** [comment]
oh ye there is no battle pass on pbe maybe will add soon

**Comment by OwOHamper** [comment]
I just change region to na when pbe is detected it should do the trick, however I am not able to test it since I don't have pbe account so when new valorant rank yoinker version gets released I will comment on this and I will be waiting for your feedback.
