### ISSUE TITLE
WinError 10060

### ISSUE THREAD

**Issue by thunderstrom1222** [zayKenyon/VALORANT-rank-yoinker#174]
[2023.09.29-18.59.19] got region from logs '['ap', ['ap-1', 'ap']]'
[2023.09.29-18.59.19] Api urls: pd_url: 'https://pd.ap.a.pvp.net', glz_url: 'https://glz-ap-1.ap.a.pvp.net'
[2023.09.29-18.59.19] opened lockfile
[2023.09.29-18.59.19] got version from logs 'release-07.06-shipping-4-983570'
[2023.09.29-18.59.49] Traceback (most recent call last):
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connection.py", line 203, in _new_conn
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\util\connection.py", line 85, in create_connection
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connectionpool.py", line 790, in urlopen
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connectionpool.py", line 1092, in _validate_conn
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connection.py", line 611, in connect
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connection.py", line 212, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x0000020329354F10>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\adapters.py", line 486, in send
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /zayKenyon/VALORANT-rank-yoinker/main/status.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020329354F10>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 99, in <module>
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\src\requestsV.py", line 68, in check_status
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\api.py", line 73, in get
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\api.py", line 59, in request
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\sessions.py", line 589, in request
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\sessions.py", line 703, in send
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\venv\Lib\site-packages\requests\adapters.py", line 507, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /zayKenyon/VALORANT-rank-yoinker/main/status.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000020329354F10>, 'Connection to raw.githubusercontent.com timed out. (connect timeout=None)'))

**Comment by zayKenyon** [comment]
Hey there! A win-error 10060 is generally due to one of these factors:

1. This may be because the port vRY uses is already in use (`1100`). 
Start off by checking your firewall settings to see if it is being blocked, temporarily disabling your firewall will confirm this. 
If needed, you could then try to restart: vRY, but if that doesn't fix it then VALORANT, but then if that doesn't fix it then your computer. 

2. If you have a slower internet connection then changing the value of `cooldown` located in `config.json` to 0 (manual refresh) or to something > 1 may help.

3. If that doesn't work then changing the port located within the `config.json` file may work.
‎
