### ISSUE TITLE
getting an error 

### ISSUE THREAD

**Issue by xlegends** [zayKenyon/VALORANT-rank-yoinker#199]
[2024.06.28-10.30.57] Operating system: Windows 11 Core 10.0.22631

[2024.06.28-10.30.57] got region from logs '['na', ['na-1', 'na']]'
[2024.06.28-10.30.57] Api urls: pd_url: 'https://pd.na.a.pvp.net', glz_url: 'https://glz-na-1.na.a.pvp.net'
[2024.06.28-10.30.57] opened lockfile
[2024.06.28-10.30.57] Traceback (most recent call last):
  File "main.py", line 97, in <module>
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\src\requestsV.py", line 31, in __init__
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\src\requestsV.py", line 206, in get_headers
KeyError: 'subject'

idk whats going on

**Comment by JeffVu-1** [comment]
doesn't seem like it works anymore I'm having the same issue

**Comment by pintoso** [comment]
try running as admin
reinstall python & restart ur pc maybe works too

> _Sorry for late response, but I think it was maybe with riot client being incorrectly initialized or something? Because if subject is missing, that usually happens if you are not logged in or something._

_- Hamper_

**Comment by xlegends** [comment]
resolved now
