### ISSUE TITLE
error - logs

### ISSUE THREAD

**Issue by UnPurgable** [zayKenyon/VALORANT-rank-yoinker#97]
[2022.08.05-14.05.49] got region from logs '['na', ['na-1', 'na']]'
[2022.08.05-14.05.49] Api urls: pd_url: 'https://pd.na.a.pvp.net', glz_url: 'https://glz-na-1.na.a.pvp.net'
[2022.08.05-14.05.49] opened lockfile
[2022.08.05-14.05.49] Traceback (most recent call last):
  File "main.py", line 65, in <module>
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\src\requests.py", line 27, in __init__
  File "C:\Users\isaac\Documents\GitHub\VALORANT-rank-yoinker\src\requests.py", line 137, in get_headers
KeyError: 'subject'

**Comment by zayKenyon** [comment]
#96
